# Generated by Django 3.1 on 2021-05-02 10:29

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.models.MyManager()),
            ],
        ),
    ]
