# Generated by Django 3.1 on 2021-05-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
